# Generated by Django 5.1.4 on 2026-08-26 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arquivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome_original", models.CharField(max_length=255)),
                ("caminho_storage", models.CharField(max_length=500, unique=True)),
                ("content_type", models.CharField(max_length=100)),
                ("tamanho_bytes", models.PositiveBigIntegerField()),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="contas.vendedor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
