# Generated by Django 5.1.4 on 2026-09-01 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arquivos", "0001_initial"),
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="foto_banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arquivos.arquivo",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto_perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arquivos.arquivo",
            ),
        ),
    ]
