# Generated by Django 5.1.4 on 2026-09-02 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0002_usuario_foto_banner_usuario_foto_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="MercadoLivreToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ml_user_id", models.BigIntegerField(unique=True)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expires_at", models.DateTimeField()),
                (
                    "vendedor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mercado_livre_token",
                        to="contas.vendedor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
