# Generated by Django 5.1.4 on 2026-10-06 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0002_usuario_foto_banner_usuario_foto_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "canal",
                    models.CharField(choices=[("MERCADO_LIVRE", "Mercado Livre")], max_length=30),
                ),
                ("id_externo", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGO", "Pago"),
                            ("CANCELADO", "Cancelado"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status_no_canal", models.CharField(max_length=50)),
                ("entregue", models.BooleanField(default=False)),
                ("realizado_em", models.DateTimeField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("valor_pago", models.DecimalField(decimal_places=2, max_digits=12)),
                ("moeda", models.CharField(max_length=3)),
                ("comprador_id_externo", models.CharField(blank=True, max_length=64)),
                ("comprador_apelido", models.CharField(blank=True, max_length=150)),
                ("sincronizado_em", models.DateTimeField()),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="contas.vendedor",
                    ),
                ),
            ],
            options={
                "ordering": ["-realizado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("id_externo", models.CharField(max_length=64)),
                ("titulo", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("quantidade", models.PositiveIntegerField()),
                ("preco_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("taxa_venda", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pedidos.pedido",
                    ),
                ),
            ],
            options={
                "ordering": ["criado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="pedido",
            constraint=models.UniqueConstraint(
                fields=("vendedor", "canal", "id_externo"), name="pedido_unico_por_canal"
            ),
        ),
    ]
